runtime: python311
entrypoint: gunicorn -b :$PORT app:app --timeout 300 --workers 1 --threads 2

instance_class: F2

env_variables:
  GCS_BUCKET_NAME: "ndvi-spectral-arrays-plucky-environs-416709"
  GOOGLE_CLOUD_PROJECT: "plucky-environs-416709"

automatic_scaling:
  min_instances: 0
  max_instances: 1
